services:
  xss:
    image: ghcr.io/aabichou/ctf-challenges-ajiz/xss:latest
    container_name: ${SUBDOMAIN}
    restart: unless-stopped
    expose:
      - ${PORT}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${SUBDOMAIN}.rule=Host(`${SUBDOMAIN}.${DOMAIN}`)"
      - "traefik.http.routers.${SUBDOMAIN}.entrypoints=websecure"

      - "traefik.http.services.${SUBDOMAIN}.loadbalancer.server.port=${PORT}"
networks:
  default:
    name: external
    external: true
