services:
  brouklou:
    image: adamab/${SUBDOMAIN}:ajiz
    container_name: ${SUBDOMAIN}
    restart: unless-stopped
    expose:
      - 80
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${SUBDOMAIN}.rule=Host(`${SUBDOMAIN}.${DOMAIN}`)"
      - "traefik.http.routers.${SUBDOMAIN}.entrypoints=web"
      - "traefik.http.services.${SUBDOMAIN}.loadbalancer.server.port=80"
networks:
  default:
    name: external
    external: true
