services:
  brouklou:
    image: adamab/${SUBDOMAIN}:ajiz
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ${SUBDOMAIN}
    restart: unless-stopped
    ports:
      - ${PORT}:${PORT}
    tty: true
    stdin_open: true # docker run -i

networks:
  default:
    name: external
    external: true
