services:
  ctfjail:
    image: ghcr.io/aabichou/ctf-challenges-ajiz/ctfjail:ajiz
    container_name: ${SUBDOMAIN}
    restart: unless-stopped
    ports:
      - ${PORT}:${PORT}
    tty: true
    stdin_open: true # docker run -i

networks:
  default:
    name: external
    external: true
